### ISSUE TITLE
url for P7699 on viaf

### ISSUE THREAD

**Issue by eru03** [arthurpsmith/wikidata-tools#21]
Hi,

See the talk here: https://www.wikidata.org/wiki/Property_talk:P7699#LIH_justlinks.json

We want to change the url formater, but then viaf url will not longer work, it needs to add an underscore around the lower case lettre and replace * with -.
For exemple : 
- LNB:2bf;=Ba > LNB:2_b__f_;=B_a_
- LNB:CNYr;=By > LNB:CNY_r_;=B_y_
- LNB:xLp;=CE > LNB:_x_L_p_;=CE
- LNB:V*1830;=0L > LNB:V-1830;=0L

It's possible ?

**Comment by Camillo-Pellizzari** [comment]
I'm collecting examples of the needed substitutions here:https://www.wikidata.org/wiki/Property_talk:P7699#Substitutions.

**Comment by arthurpsmith** [comment]
@eru03 this seems straightforward enough; if you want to update the code yourself you can do it via a github pull request, or just let me know when you've settled exactly what needs to be done to transform the id's for this.

**Comment by eru03** [comment]
sorry, bad click...

**Comment by eru03** [comment]
Hi, 
Done : https://github.com/arthurpsmith/wikidata-tools/pull/22
I tested it here : 

- https://benoit-guillaume.fr/wikidata-externalid-url/?p=7699&url_prefix=https://viaf.org/processed/LIH%7C&id=LNB:2bf;=Ba
- https://benoit-guillaume.fr/wikidata-externalid-url/?p=7699&url_prefix=https://viaf.org/processed/LIH%7C&id=LNB:O%2B%2B;=1A
- https://benoit-guillaume.fr/wikidata-externalid-url/?p=7699&url_prefix=https://viaf.org/processed/LIH%7C&id=LNB:/fy;=B6
- https://benoit-guillaume.fr/wikidata-externalid-url/?p=7699&url_prefix=https://viaf.org/processed/LIH%7C&id=LNB:V*159888436;=Bm

**Comment by eru03** [comment]
Thanks, it's work well
