### ISSUE TITLE
url for P1207 (NUKAT ID)

### ISSUE THREAD

**Issue by Camillo-Pellizzari** [arthurpsmith/wikidata-tools#23]
Hi! The formatter URL of https://www.wikidata.org/wiki/Property:P1207 should be http://nukat.edu.pl/aut/$1; however, our actual $1 is "n" followed by 8 or 10 numbers, while in the formatter URL there should be two spaces (%20%20) between "n" and the numbers. So e.g. https://www.wikidata.org/wiki/Q42552, which has n94201670, should point to http://nukat.edu.pl/aut/n%20%2094201670. Would it be possible? Thanks!

**Comment by arthurpsmith** [comment]
This is implemented in the web service at toolforge, but somebody will have to update the formatter URL to use it - the new formatter should be: https://wikidata-externalid-url.toolforge.org/?p=1207&url_prefix=http://nukat.edu.pl/aut/&id=$1
