### ISSUE TITLE
External ID tool redirects to invalid URL if not given property ID

### ISSUE THREAD

**Issue by lucaswerkmeister** [arthurpsmith/wikidata-tools#28]
Due to this default behavior:

```php
  default:
    if (! empty($exp) ) {
      preg_match('/'.$exp.'/', $id, $a);
      for($i=0; $i<sizeof($a); $i++) {
        $url = str_replace("%".$i, $a[$i], $url);
      }
      $link_string = $url;
    }
    else
      $link_string = $id ;
    break;
    

    break ;
 }

 $redirect_url = $url_prefix . $link_string . $url_suffix ;
 header("Location: $redirect_url");
 exit();
}
```

The tool redirects even when not given any property ID or other information to build a URL out of, for example:
```console
$ curl -sI 'https://wikidata-externalid-url.toolforge.org/?id=12345' | grep -i location
location: 12345
```
Clickable link: https://wikidata-externalid-url.toolforge.org/?id=12345

This can also be used to create [open redirects](https://cwe.mitre.org/data/definitions/601.html) in a simpler way than #5:
```console
$ curl -sI 'https://wikidata-externalid-url.toolforge.org/?id=https://tinyurl.com/hb9897q' | grep -i location
location: https://tinyurl.com/hb9897q
```

**Comment by arthurpsmith** [comment]
Hi @lucaswerkmeister I'm trying to understand what are the circumstances where this (or #5) would be an issue. Within Wikidata this tool is used for formatter URL's so the links to the tool should always be constructed by the Wikidata UI based on statements on a property entity, and property edits are I believe at least semi-protected so this shouldn't be a source of vandalism.
So are we envisioning people adding direct links to this tool on Mediawiki pages somewhere? Wouldn't that be like adding links to any other site that might redirect elsewhere (like doi.org)? What's the scenario here where this is actually a problem?

**Comment by lucaswerkmeister** [comment]
> So are we envisioning people adding direct links to this tool on Mediawiki pages somewhere?

Yes (among other places). For example, right now I can’t link to `torrentmania.info` on any Wikimedia wiki, because that domain is on the spam blacklist; but because this tool has open redirect vulnerabilities, I can link to e.g. `https://wikidata-externalid-url.toolforge.org/?id=https://torrentmania.info/` and achieve the same thing. (Replace `torrentmania.info` with any phishing site.)

> Wouldn't that be like adding links to any other site that might redirect elsewhere (like doi.org)?

No, because doi.org doesn’t redirect to any arbitrary website (or so I assume). To take another example, tinyurl.com *does* redirect to any arbitrary website, and consequently it’s on the [spam blacklist](https://meta.wikimedia.org/wiki/Spam_blacklist), along with over four hundred other URL shorteners. It’s the *open* redirect that’s the problem.

> What's the scenario here where this is actually a problem?

See e.g. [T151977](https://phabricator.wikimedia.org/T151977) for an instance where an open redirect on *.wikimedia.org was actively being abused as a way to get around a spam whitelist.

**Comment by arthurpsmith** [comment]
Ok, this is the same issue as #5 then. I think the only viable solution is to compare the redirect URL's to the spam blacklist, so I'll need to implement that.

**Comment by lucaswerkmeister** [comment]
I don’t think that’s the only viable solution, and in fact I think it would be miserable to implement. (At least MediaWiki only has to check the SpamBlacklist when an edit is saved – without some kind of caching, you’d have to do it on every request…)

I think a much better approach would be to more tightly control (from the point of view of the tool) the URLs that the tool redirects to, instead of taking so much information from the URL parameters. For example, you pointed out in #29 that the code for P213 just removes spaces, but is it actually necessary for that property ID to be able to redirect to any arbitrary domain? Surely that should always point to isni.org?

I think this would mainly mean removing support for the `url_prefix` and similar things _as URL parameters_ – instead, the tool should have this information hard-coded (P213 ⇒ prefix with `http://isni.org/`, always). That makes the tool less flexible, sure, but I think it’s a much better solution than checking the redirect target against the Wikimedia spam blacklist.

**Comment by arthurpsmith** [comment]
No, it's not nearly that simple - not even for P213, check the history there on changes to the formatter URL (the current preferred formatter is at isni.oclc.org with some extra parameters). Forcing people to do pull requests on this code instead of editing the formatters at wikidata seems like a pretty heavy burden.

Can you remind me where the toolforge service monitoring pages are? I don't have access logs for this service so I'm not sure the level of burden it would be on it to do the blacklist check. With blacklist checking/caching is it sufficient to just cache the yes/no answer of the first part of the URL (http(s)://xxx.yyy.zzz/)? I think that would actually end up being a pretty light load issue.

**Comment by lucaswerkmeister** [comment]
I didn’t say it would be simple. This tool tries to build valid URLs out of “fragments” for dozens of idiosyncratic websites, where the only common factor is that the fragment→URL conversion is *not* simple enough for a direct formatter URL – I think that’s an inherently complex task.

If you don’t want to hard-code the information into the tool, I suppose it could also read some kind of configuration file, e.g. from a semi-protected wiki page. It just has to be a source with some level of trust, unlike the request URL which should be treated as totally untrusted.

I don’t know if there are any general Toolforge tool usage stats – I didn’t find any, at least.

Strictly speaking, checking just the domain against the spam blacklist isn’t enough, because some of the entries match on the path (e.g. `jeeee\.net/url`). But an allowlist of domains might be an easy way to make the supported redirect targets configurable (put the list of allowed domains on a semi-protected wiki page, and then trust that the editors won’t allowlist a spam-blacklisted domain), which could be much more efficient than checking against the full spam blacklist.

**Comment by arthurpsmith** [comment]
I thought there was something under https://grafana-labs.wikimedia.org/ ??
I almost have the blacklist checking working, but it looks like adding caching will be a bit painful. Symfony seems to be the package to use for that in php nowadays?

**Comment by arthurpsmith** [comment]
Hmm, do you understand these "url" blocks? What is \bgoogle\..*?/url\?.* trying to block?

**Comment by arthurpsmith** [comment]
Ok, I've implemented blacklist with caching, along with some up-front white- and black-listing without querying the wikidata api to limit the rate of those queries. Seems to be running just fine, looks like doing about one API query per minute right now (which will hopefully decrease once the cache fills a bit). The examples you provided above are blocked.

**Comment by lucaswerkmeister** [comment]
> Hmm, do you understand these "url" blocks? What is \bgoogle.._?/url?._ trying to block?

That’s an open redirect at Google, e.g. [this google.com URL](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwinudf1pcT4AhUFi_0HHbUtC7AQFnoECBIQAQ&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FMain_Page&usg=AOvVaw1rzc4UVx4rSWqA-Z7DQ3um) redirects to en.wikipedia.org. It’s used in search results, apparently.

**Comment by lucaswerkmeister** [comment]
Also, your fix introduced an XSS vulnerability.

https://wikidata-externalid-url.toolforge.org/?id=%3Cscript%3Ealert(%27xss%27)%3C/script%3E
![image](https://user-images.githubusercontent.com/2346599/175381371-54fb003b-6531-4ec4-801f-1f56b28845f4.png)

**Comment by arthurpsmith** [comment]
Ok, I just won't redisplay the bogus input at all. Should be good now.
