### ISSUE TITLE
WebFinger should be used to find Mastodon profile URL

### ISSUE THREAD

**Issue by russss** [arthurpsmith/wikidata-tools#30]
For example, this doesn't work, despite the address being valid: https://wikidata-externalid-url.toolforge.org/?p=4033&id=emf@emfcamp.org (from [Q5358069](https://www.wikidata.org/wiki/Q5358069))

The script is currently just taking the domain (emfcamp.org) and appending `/@emf`. While this works in most cases where the server is running Mastodon, it's not strictly correct, and it doesn't work in this instance.

The correct way to find the profile URL for a Mastodon address is using [WebFinger](https://www.rfc-editor.org/rfc/rfc7033.html) - basically fetch the following JSON document from the domain of the Mastodon address:

https://emfcamp.org/.well-known/webfinger?resource=acct:emf@emfcamp.org

Then (possibly after some redirects), the result is the item in `links` with `rel`=`http://webfinger.net/rel/profile-page`.

**Comment by Krinkle** [comment]
The same issue is happening with for example https://mastodon.macstories.net/@macstories at [Q123308619](https://www.wikidata.org/wiki/Q123308619).

The canonical handle, which the Wikidata property insists on as input, is `@macstories@macstories.net`. Yet, this is then linked as https://wikidata-externalid-url.toolforge.org/?p=4033&id=%40macstories%40macstories.net which incorrectly points to the non-existant `https://www.macstories.net/@macstories`.

**Comment by arthurpsmith** [comment]
Hi @russss  and @Krinkle - this is out of scope for this service. It needs to be self-contained, not calling external services. I suggest somebody writes a proper resolver for mastodon/fediverse canonical addresses and then replace this service with that one in the Wikidata resolver.
