### ISSUE TITLE
Twitter user ID (P6552)

### ISSUE THREAD

**Issue by nicolasmaia** [arthurpsmith/wikidata-tools#4]
Not sure if this is currently possible, but it would be ideal to have the user ID page redirect to the actual user page. Relevant property: https://www.wikidata.org/wiki/Property:P6552

Here's an example for [Q28804296](https://www.wikidata.org/wiki/Q28804296): https://twitter.com/intent/user?user_id=912560248963063808 should redirect to https://twitter.com/kafejosojo

At the bottom of the user ID page there is a direct link to the Twitter profile.

**Comment by arthurpsmith** [comment]
This is way beyond the current scope of this tool which basically just does some logical string rewriting. It sounds like this could be done via a query to the twitter API - if this becomes a real need I could look into it, or if somebody else wants to point me to how to do it via PHP I would probably be more eager to work on it...

**Comment by arthurpsmith** [comment]
Closing - too much has changed.
