### ISSUE TITLE
Bad gateway

### ISSUE THREAD

**Issue by 4ing** [arthurpsmith/wikidata-tools#6]
Not able to open any Imdb links from Wikidata since ~Friday last week. Error message: 502 Bad Gateway

**Comment by arthurpsmith** [comment]
Wow, I'm not sure what happened. I restarted the webservice and it seems to be working fine now. Tools labs recently made me move it to a new kubernetes cloud but I haven't had any problems with that until now, and hadn't heard about other people having trouble there. I'll keep a closer eye on it, see if I can find out what happened. Thanks for the report!

**Comment by 4ing** [comment]
Should this edit be reverted then? It works fine not only for Imdb name, I've checked that it also works for Imdb title:

https://www.wikidata.org/w/index.php?title=Property%3AP345&type=revision&diff=886768852&oldid=886607254

**Comment by arthurpsmith** [comment]
Probably should - it works for some of the id types but it looks like not all of them.
