### ISSUE TITLE
Support Gamepedia article (P6623) in wikidata-externalid-url

### ISSUE THREAD

**Issue by jc86035** [arthurpsmith/wikidata-tools#7]
P6623 was created prematurely without a working formatter URL.

It is apparently not possible to make a formatter URL with only one variable, because Gamepedia's interwiki table is incomplete; each wiki uses a different table and most of the wikis have nothing to do with each other. https://help.gamepedia.com has `https://$1.gamepedia.com` for `w:`, but this doesn't work for individual pages (e.g. searching `w:wow:Faction` results in a redirect to `https://wow:faction.gamepedia.com`, which is invalid).

I asked through their Zendesk support system and received a reply indicating that an interwiki system does not exist, but that `https://$1.gamepedia.com` should be sufficient for all Gamepedia wikis, even those that use custom domain names.

As such, since values are to be input in the format `wiki-id:page-title`, what the PHP script should do is
* split the value at the colon, and remove the colon
* format the URL as `https://wiki-id.gamepedia.com/page-title`

**Comment by arthurpsmith** [comment]
Shouldn't be hard to do, I'l take a look now.

**Comment by arthurpsmith** [comment]
Ok, should be working now! I'll update the formatter URL.
