### ISSUE TITLE
Support for more characters to escape?

### ISSUE THREAD

**Issue by egonw** [arthurpsmith/wikidata-tools#9]
Currently, SMILES strings sometimes fail in the `formatter URL` ([P233](https://www.wikidata.org/wiki/Property:P233) and [P2017](https://www.wikidata.org/wiki/Property:P2017)) because of characters that need to be escape. These are (valid) SMILES examples for which the formatted URL doesn't work:

* C#N
* C/C=C/C

Would it be technically possible to have support to escape these from the input too?

**Comment by arthurpsmith** [comment]
I think it should work if you just use the redirector directly - do you have an example of items which need these characters that we could try this on?

**Comment by egonw** [comment]
Of the first check [Q26075](https://www.wikidata.org/wiki/Q26075) (which gets depicted as methane, as he N is lost). An example of the second I would show the trans-butene, but that one actually work (now). I will file more examples when I run into them, as I'm sure there was a second character that needed escaping :(

**Comment by arthurpsmith** [comment]
Are you using a gadget that tries to link that SMILES value? All I see is a plain string (canonical SMILES is not in the identifiers section)

**Comment by arthurpsmith** [comment]
Closing - stale.
